-- ===========================================================================
-- 014: Phase 3A — SKU Classification & Master Data Import
--
-- Auto-generated by classify_skus.py
-- Generated: 2026-02-14 15:41:04
--
-- Data sources:
--   ItemActivityInventoryDepletion.xlsx (Avg Ship/Wk)
--   ViewItem (3).xlsx (Cost, Weight, Dimensions)
--   Item_Activity_Report (1-6).xlsx (Monthly CV)
--
-- Prerequisites: 001-013 must have been run
-- ===========================================================================


-- =============================================
-- PART 1: Add new columns to skus table
-- =============================================

ALTER TABLE skus ADD COLUMN IF NOT EXISTS unit_cost NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS annual_consumption_value NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS avg_weekly_demand NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS cv_demand NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS dimensions_cbm NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS length_in NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS width_in NUMERIC;
ALTER TABLE skus ADD COLUMN IF NOT EXISTS height_in NUMERIC;


-- =============================================
-- PART 2: Update/Insert SKU master data + classification
-- =============================================

-- 1282199GT: AX | $972,284/yr | Avg 14.3/wk | CV=0.2979 | Cost $1303.68
UPDATE skus SET
  unit_cost = 1303.6800,
  unit_weight = 3999.0000,
  abc_class = 'A',
  xyz_class = 'X',
  annual_consumption_value = 972284.02,
  avg_weekly_demand = 14.3423,
  cv_demand = 0.2979,
  dimensions_cbm = 1.367107,
  length_in = 59.00,
  width_in = 28.00,
  height_in = 50.50,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '1282199GT'
   OR sku_code = '1282199'
   OR sku_code = '1282199GTGT';

-- 1277620GT: AY | $729,086/yr | Avg 12.2/wk | CV=0.9402 | Cost $1151.97
UPDATE skus SET
  unit_cost = 1151.9727,
  unit_weight = 2145.1000,
  abc_class = 'A',
  xyz_class = 'Y',
  annual_consumption_value = 729086.29,
  avg_weekly_demand = 12.1712,
  cv_demand = 0.9402,
  dimensions_cbm = 1.409342,
  length_in = 86.61,
  width_in = 21.00,
  height_in = 47.28,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1277620GT'
   OR sku_code = '1277620'
   OR sku_code = '1277620GTGT';

-- 61415GT: AZ | $722,739/yr | Avg 5.6/wk | CV=1.4053 | Cost $2500.46
UPDATE skus SET
  unit_cost = 2500.4626,
  unit_weight = 7250.0000,
  abc_class = 'A',
  xyz_class = 'Z',
  annual_consumption_value = 722738.71,
  avg_weekly_demand = 5.5585,
  cv_demand = 1.4053,
  dimensions_cbm = 0.886868,
  length_in = 88.00,
  width_in = 41.00,
  height_in = 15.00,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '61415GT'
   OR sku_code = '61415'
   OR sku_code = '61415GTGT';

-- 1306776GT: AY | $588,647/yr | Avg 46.1/wk | CV=0.5465 | Cost $245.80
UPDATE skus SET
  unit_cost = 245.8015,
  unit_weight = 1758.0000,
  abc_class = 'A',
  xyz_class = 'Y',
  annual_consumption_value = 588647.40,
  avg_weekly_demand = 46.0540,
  cv_demand = 0.5465,
  dimensions_cbm = 7.604892,
  length_in = 110.00,
  width_in = 123.00,
  height_in = 34.30,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1306776GT'
   OR sku_code = '1306776'
   OR sku_code = '1306776GTGT';

-- 824433GT: AY | $433,980/yr | Avg 3.6/wk | CV=0.8068 | Cost $2310.18
UPDATE skus SET
  unit_cost = 2310.1840,
  unit_weight = 7028.0000,
  abc_class = 'A',
  xyz_class = 'Y',
  annual_consumption_value = 433980.08,
  avg_weekly_demand = 3.6126,
  cv_demand = 0.8068,
  dimensions_cbm = 3.207571,
  length_in = 101.00,
  width_in = 38.00,
  height_in = 51.00,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '824433GT'
   OR sku_code = '824433'
   OR sku_code = '824433GTGT';

-- 1267365GT: BZ | $364,957/yr | Avg 2.2/wk | CV=1.7710 | Cost $3192.80
UPDATE skus SET
  unit_cost = 3192.7980,
  unit_weight = 8309.0000,
  abc_class = 'B',
  xyz_class = 'Z',
  annual_consumption_value = 364957.25,
  avg_weekly_demand = 2.1982,
  cv_demand = 1.7710,
  dimensions_cbm = 2.240264,
  length_in = 88.58,
  width_in = 31.50,
  height_in = 49.00,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1267365GT'
   OR sku_code = '1267365'
   OR sku_code = '1267365GTGT';

-- 1301444GT: BY | $99,826/yr | Avg 7.3/wk | CV=0.5456 | Cost $262.43
UPDATE skus SET
  unit_cost = 262.4266,
  unit_weight = 4834.6560,
  abc_class = 'B',
  xyz_class = 'Y',
  annual_consumption_value = 99825.92,
  avg_weekly_demand = 7.3153,
  cv_demand = 0.5456,
  dimensions_cbm = 0.983361,
  length_in = 53.15,
  width_in = 47.64,
  height_in = 23.70,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1301444GT'
   OR sku_code = '1301444'
   OR sku_code = '1301444GTGT';

-- 1299677GT: BY | $65,006/yr | Avg 21.9/wk | CV=0.5328 | Cost $57.03
UPDATE skus SET
  unit_cost = 57.0333,
  unit_weight = 2262.3456,
  abc_class = 'B',
  xyz_class = 'Y',
  annual_consumption_value = 65005.57,
  avg_weekly_demand = 21.9189,
  cv_demand = 0.5328,
  dimensions_cbm = 0.319356,
  length_in = 25.59,
  width_in = 27.95,
  height_in = 27.24,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1299677GT'
   OR sku_code = '1299677'
   OR sku_code = '1299677GTGT';

-- 1278414GT: BX | $48,419/yr | Avg 2.5/wk | CV=0.3186 | Cost $371.79
UPDATE skus SET
  unit_cost = 371.7850,
  unit_weight = 1024.7200,
  abc_class = 'B',
  xyz_class = 'X',
  annual_consumption_value = 48419.05,
  avg_weekly_demand = 2.5045,
  cv_demand = 0.3186,
  dimensions_cbm = 0.149450,
  length_in = 38.00,
  width_in = 12.00,
  height_in = 20.00,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1278414GT'
   OR sku_code = '1278414'
   OR sku_code = '1278414GTGT';

-- 1278415GT: BX | $48,419/yr | Avg 2.5/wk | CV=0.3186 | Cost $371.79
UPDATE skus SET
  unit_cost = 371.7850,
  unit_weight = 1024.7200,
  abc_class = 'B',
  xyz_class = 'X',
  annual_consumption_value = 48419.05,
  avg_weekly_demand = 2.5045,
  cv_demand = 0.3186,
  dimensions_cbm = 0.149450,
  length_in = 38.00,
  width_in = 12.00,
  height_in = 20.00,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1278415GT'
   OR sku_code = '1278415'
   OR sku_code = '1278415GTGT';

-- 1272762GT: BZ | $43,652/yr | Avg 1.9/wk | CV=1.5545 | Cost $445.84
UPDATE skus SET
  unit_cost = 445.8354,
  unit_weight = 1068.0000,
  abc_class = 'B',
  xyz_class = 'Z',
  annual_consumption_value = 43652.10,
  avg_weekly_demand = 1.8829,
  cv_demand = 1.5545,
  dimensions_cbm = 0.309371,
  length_in = 31.00,
  width_in = 21.00,
  height_in = 29.00,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '1272762GT'
   OR sku_code = '1272762'
   OR sku_code = '1272762GTGT';

-- 1272913GT: BZ | $42,398/yr | Avg 1.8/wk | CV=1.5591 | Cost $445.84
UPDATE skus SET
  unit_cost = 445.8354,
  unit_weight = 1068.0000,
  abc_class = 'B',
  xyz_class = 'Z',
  annual_consumption_value = 42397.88,
  avg_weekly_demand = 1.8288,
  cv_demand = 1.5591,
  dimensions_cbm = 0.309371,
  length_in = 31.00,
  width_in = 21.00,
  height_in = 29.00,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '1272913GT'
   OR sku_code = '1272913'
   OR sku_code = '1272913GTGT';

-- 78680GT: BX | $42,242/yr | Avg 113.6/wk | CV=0.3647 | Cost $7.15
UPDATE skus SET
  unit_cost = 7.1529,
  unit_weight = 0.0000,
  abc_class = 'B',
  xyz_class = 'X',
  annual_consumption_value = 42241.52,
  avg_weekly_demand = 113.5675,
  cv_demand = 0.3647,
  dimensions_cbm = 1.099991,
  length_in = 43.31,
  width_in = 39.37,
  height_in = 39.37,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '78680GT'
   OR sku_code = '78680'
   OR sku_code = '78680GTGT';

-- 1270247GT: BY | $33,358/yr | Avg 4.1/wk | CV=0.8881 | Cost $156.84
UPDATE skus SET
  unit_cost = 156.8403,
  unit_weight = 408.9799,
  abc_class = 'B',
  xyz_class = 'Y',
  annual_consumption_value = 33357.61,
  avg_weekly_demand = 4.0901,
  cv_demand = 0.8881,
  dimensions_cbm = 0.124645,
  length_in = 27.17,
  width_in = 20.00,
  height_in = 14.00,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1270247GT'
   OR sku_code = '1270247'
   OR sku_code = '1270247GTGT';

-- 1277619GT: CY | $26,737/yr | Avg 0.8/wk | CV=0.9009 | Cost $607.21
UPDATE skus SET
  unit_cost = 607.2058,
  unit_weight = 2145.1000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 26737.46,
  avg_weekly_demand = 0.8468,
  cv_demand = 0.9009,
  dimensions_cbm = 1.476448,
  length_in = 86.61,
  width_in = 22.00,
  height_in = 47.28,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1277619GT'
   OR sku_code = '1277619'
   OR sku_code = '1277619GTGT';

-- 56174GT: CX | $25,789/yr | Avg 4.2/wk | CV=0.3016 | Cost $118.64
UPDATE skus SET
  unit_cost = 118.6400,
  unit_weight = 761.9047,
  abc_class = 'C',
  xyz_class = 'X',
  annual_consumption_value = 25788.82,
  avg_weekly_demand = 4.1802,
  cv_demand = 0.3016,
  dimensions_cbm = 0.671456,
  length_in = 36.61,
  width_in = 29.92,
  height_in = 37.40,
  supplier_code = 'WINSCHEM',
  updated_at = NOW()
WHERE sku_code = '56174GT'
   OR sku_code = '56174'
   OR sku_code = '56174GTGT';

-- 1301777GT: CY | $14,083/yr | Avg 2.2/wk | CV=0.8000 | Cost $125.26 (XYZ estimated)
UPDATE skus SET
  unit_cost = 125.2586,
  unit_weight = 3613.7563,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 14083.38,
  avg_weekly_demand = 2.1622,
  cv_demand = 0.8000,
  dimensions_cbm = 0.640784,
  length_in = 44.88,
  width_in = 30.31,
  height_in = 28.74,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1301777GT'
   OR sku_code = '1301777'
   OR sku_code = '1301777GTGT';

-- 1287893GT: CY | $12,560/yr | Avg 0.4/wk | CV=0.6838 | Cost $670.22
UPDATE skus SET
  unit_cost = 670.2200,
  unit_weight = 1749.9760,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 12560.46,
  avg_weekly_demand = 0.3604,
  cv_demand = 0.6838,
  dimensions_cbm = 0.333322,
  length_in = 45.28,
  width_in = 36.81,
  height_in = 12.20,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1287893GT'
   OR sku_code = '1287893'
   OR sku_code = '1287893GTGT';

-- 1277749GT: CY | $11,698/yr | Avg 0.5/wk | CV=0.6251 | Cost $499.36
UPDATE skus SET
  unit_cost = 499.3600,
  unit_weight = 1267.3000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 11698.01,
  avg_weekly_demand = 0.4505,
  cv_demand = 0.6251,
  dimensions_cbm = 0.558890,
  length_in = 67.91,
  width_in = 42.52,
  height_in = 11.81,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1277749GT'
   OR sku_code = '1277749'
   OR sku_code = '1277749GTGT';

-- 1287172GT: CY | $10,194/yr | Avg 2.4/wk | CV=0.8000 | Cost $80.59 (XYZ estimated)
UPDATE skus SET
  unit_cost = 80.5909,
  unit_weight = 990.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 10193.52,
  avg_weekly_demand = 2.4324,
  cv_demand = 0.8000,
  dimensions_cbm = 0.188877,
  length_in = 113.00,
  width_in = 34.00,
  height_in = 3.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287172GT'
   OR sku_code = '1287172'
   OR sku_code = '1287172GTGT';

-- 1287173GT: CY | $9,325/yr | Avg 2.2/wk | CV=0.8000 | Cost $80.59 (XYZ estimated)
UPDATE skus SET
  unit_cost = 80.5909,
  unit_weight = 990.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 9325.21,
  avg_weekly_demand = 2.2252,
  cv_demand = 0.8000,
  dimensions_cbm = 0.188877,
  length_in = 113.00,
  width_in = 34.00,
  height_in = 3.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287173GT'
   OR sku_code = '1287173'
   OR sku_code = '1287173GTGT';

-- 1306370GT: CY | $8,624/yr | Avg 1.9/wk | CV=0.8000 | Cost $86.02 (XYZ estimated)
UPDATE skus SET
  unit_cost = 86.0249,
  unit_weight = 1200.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 8624.07,
  avg_weekly_demand = 1.9279,
  cv_demand = 0.8000,
  dimensions_cbm = 0.046212,
  length_in = 47.00,
  width_in = 15.00,
  height_in = 4.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1306370GT'
   OR sku_code = '1306370'
   OR sku_code = '1306370GTGT';

-- 1254649GT: CY | $7,192/yr | Avg 210.2/wk | CV=0.6000 | Cost $0.66 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.6580,
  unit_weight = 0.1700,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 7191.53,
  avg_weekly_demand = 210.1802,
  cv_demand = 0.6000,
  dimensions_cbm = 0.000225,
  length_in = 5.50,
  width_in = 5.00,
  height_in = 0.50,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1254649GT'
   OR sku_code = '1254649'
   OR sku_code = '1254649GTGT';

-- 1287191GT: CY | $6,589/yr | Avg 2.0/wk | CV=0.8000 | Cost $64.52 (XYZ estimated)
UPDATE skus SET
  unit_cost = 64.5171,
  unit_weight = 639.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 6589.00,
  avg_weekly_demand = 1.9640,
  cv_demand = 0.8000,
  dimensions_cbm = 0.039575,
  length_in = 46.00,
  width_in = 21.00,
  height_in = 2.50,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287191GT'
   OR sku_code = '1287191'
   OR sku_code = '1287191GTGT';

-- 1287190GT: CY | $6,203/yr | Avg 2.2/wk | CV=0.8000 | Cost $55.17 (XYZ estimated)
UPDATE skus SET
  unit_cost = 55.1727,
  unit_weight = 660.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 6203.31,
  avg_weekly_demand = 2.1622,
  cv_demand = 0.8000,
  dimensions_cbm = 0.053962,
  length_in = 70.25,
  width_in = 37.50,
  height_in = 1.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287190GT'
   OR sku_code = '1287190'
   OR sku_code = '1287190GTGT';

-- 1304828GT: CZ | $6,126/yr | Avg 0.6/wk | CV=1.2000 | Cost $207.56 (XYZ estimated)
UPDATE skus SET
  unit_cost = 207.5606,
  unit_weight = 6176.3661,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 6126.19,
  avg_weekly_demand = 0.5676,
  cv_demand = 1.2000,
  dimensions_cbm = 0.456277,
  length_in = 45.00,
  width_in = 45.00,
  height_in = 13.75,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1304828GT'
   OR sku_code = '1304828'
   OR sku_code = '1304828GTGT';

-- 60342GT: CY | $5,556/yr | Avg 3.6/wk | CV=0.6444 | Cost $29.65
UPDATE skus SET
  unit_cost = 29.6524,
  unit_weight = 9.9208,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 5556.48,
  avg_weekly_demand = 3.6036,
  cv_demand = 0.6444,
  dimensions_cbm = 0.000016,
  length_in = 1.00,
  width_in = 1.00,
  height_in = 1.00,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '60342GT'
   OR sku_code = '60342'
   OR sku_code = '60342GTGT';

-- 1287189GT: CY | $5,397/yr | Avg 1.9/wk | CV=0.8000 | Cost $53.34 (XYZ estimated)
UPDATE skus SET
  unit_cost = 53.3355,
  unit_weight = 1144.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 5396.85,
  avg_weekly_demand = 1.9459,
  cv_demand = 0.8000,
  dimensions_cbm = 0.053962,
  length_in = 70.25,
  width_in = 37.50,
  height_in = 1.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287189GT'
   OR sku_code = '1287189'
   OR sku_code = '1287189GTGT';

-- 1287693GT: CY | $5,152/yr | Avg 2.0/wk | CV=0.8000 | Cost $48.45 (XYZ estimated)
UPDATE skus SET
  unit_cost = 48.4469,
  unit_weight = 412.5000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 5151.84,
  avg_weekly_demand = 2.0450,
  cv_demand = 0.8000,
  dimensions_cbm = 0.032446,
  length_in = 44.00,
  width_in = 20.00,
  height_in = 2.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287693GT'
   OR sku_code = '1287693'
   OR sku_code = '1287693GTGT';

-- 1296913GT: CY | $4,609/yr | Avg 5.5/wk | CV=0.8000 | Cost $16.21 (XYZ estimated)
UPDATE skus SET
  unit_cost = 16.2095,
  unit_weight = 4.1248,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 4609.37,
  avg_weekly_demand = 5.4685,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000095,
  length_in = 10.50,
  width_in = 2.20,
  height_in = 0.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1296913GT'
   OR sku_code = '1296913'
   OR sku_code = '1296913GTGT';

-- 1287329GT: CY | $2,787/yr | Avg 2.0/wk | CV=0.8000 | Cost $27.41 (XYZ estimated)
UPDATE skus SET
  unit_cost = 27.4149,
  unit_weight = 300.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 2787.00,
  avg_weekly_demand = 1.9550,
  cv_demand = 0.8000,
  dimensions_cbm = 0.010421,
  length_in = 37.00,
  width_in = 13.75,
  height_in = 1.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287329GT'
   OR sku_code = '1287329'
   OR sku_code = '1287329GTGT';

-- 1287325GT: CY | $2,769/yr | Avg 1.9/wk | CV=0.8000 | Cost $27.62 (XYZ estimated)
UPDATE skus SET
  unit_cost = 27.6165,
  unit_weight = 300.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 2768.58,
  avg_weekly_demand = 1.9279,
  cv_demand = 0.8000,
  dimensions_cbm = 0.010611,
  length_in = 37.00,
  width_in = 14.00,
  height_in = 1.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1287325GT'
   OR sku_code = '1287325'
   OR sku_code = '1287325GTGT';

-- 1304831GT: CZ | $2,609/yr | Avg 0.4/wk | CV=1.2000 | Cost $116.04 (XYZ estimated)
UPDATE skus SET
  unit_cost = 116.0412,
  unit_weight = 2417.9894,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 2609.16,
  avg_weekly_demand = 0.4324,
  cv_demand = 1.2000,
  dimensions_cbm = 0.325485,
  length_in = 52.76,
  width_in = 27.56,
  height_in = 13.66,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1304831GT'
   OR sku_code = '1304831'
   OR sku_code = '1304831GTGT';

-- 1288782GT: CY | $1,594/yr | Avg 1.9/wk | CV=0.8000 | Cost $16.13 (XYZ estimated)
UPDATE skus SET
  unit_cost = 16.1300,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 1594.40,
  avg_weekly_demand = 1.9009,
  cv_demand = 0.8000,
  dimensions_cbm = 0.008905,
  length_in = 23.50,
  width_in = 9.25,
  height_in = 2.50,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1288782GT'
   OR sku_code = '1288782'
   OR sku_code = '1288782GTGT';

-- 1296914GT: CY | $1,478/yr | Avg 1.8/wk | CV=0.8000 | Cost $15.47 (XYZ estimated)
UPDATE skus SET
  unit_cost = 15.4685,
  unit_weight = 3.9771,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 1478.26,
  avg_weekly_demand = 1.8378,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000931,
  length_in = 101.00,
  width_in = 2.25,
  height_in = 0.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1296914GT'
   OR sku_code = '1296914'
   OR sku_code = '1296914GTGT';

-- 60863GT: CY | $1,178/yr | Avg 1.3/wk | CV=0.7733 | Cost $17.83
UPDATE skus SET
  unit_cost = 17.8280,
  unit_weight = 5.7320,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 1177.64,
  avg_weekly_demand = 1.2703,
  cv_demand = 0.7733,
  dimensions_cbm = 0.000016,
  length_in = 1.00,
  width_in = 1.00,
  height_in = 1.00,
  supplier_code = 'HX',
  updated_at = NOW()
WHERE sku_code = '60863GT'
   OR sku_code = '60863'
   OR sku_code = '60863GTGT';

-- 1291397GT: CY | $854/yr | Avg 3.4/wk | CV=0.8000 | Cost $4.87 (XYZ estimated)
UPDATE skus SET
  unit_cost = 4.8719,
  unit_weight = 1.3200,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 853.60,
  avg_weekly_demand = 3.3694,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000401,
  length_in = 8.00,
  width_in = 1.75,
  height_in = 1.75,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1291397GT'
   OR sku_code = '1291397'
   OR sku_code = '1291397GTGT';

-- 1294067GT: CY | $808/yr | Avg 3.8/wk | CV=0.8000 | Cost $4.09 (XYZ estimated)
UPDATE skus SET
  unit_cost = 4.0882,
  unit_weight = 0.8818,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 808.21,
  avg_weekly_demand = 3.8018,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000451,
  length_in = 11.00,
  width_in = 2.50,
  height_in = 1.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1294067GT'
   OR sku_code = '1294067'
   OR sku_code = '1294067GTGT';

-- 1295212GT: CY | $733/yr | Avg 3.6/wk | CV=0.8000 | Cost $3.92 (XYZ estimated)
UPDATE skus SET
  unit_cost = 3.9220,
  unit_weight = 2.7999,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 733.10,
  avg_weekly_demand = 3.5946,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000799,
  length_in = 6.50,
  width_in = 6.00,
  height_in = 1.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1295212GT'
   OR sku_code = '1295212'
   OR sku_code = '1295212GTGT';

-- 1301434GT: CZ | $656/yr | Avg 0.4/wk | CV=1.2000 | Cost $31.83 (XYZ estimated)
UPDATE skus SET
  unit_cost = 31.8346,
  unit_weight = 10.3617,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 656.20,
  avg_weekly_demand = 0.3964,
  cv_demand = 1.2000,
  dimensions_cbm = 0.000016,
  length_in = 1.00,
  width_in = 1.00,
  height_in = 1.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1301434GT'
   OR sku_code = '1301434'
   OR sku_code = '1301434GTGT';

-- 1294814GT: CY | $576/yr | Avg 2.0/wk | CV=0.8000 | Cost $5.54 (XYZ estimated)
UPDATE skus SET
  unit_cost = 5.5368,
  unit_weight = 2.0283,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 575.83,
  avg_weekly_demand = 2.0000,
  cv_demand = 0.8000,
  dimensions_cbm = 0.008923,
  length_in = 8.25,
  width_in = 8.25,
  height_in = 8.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1294814GT'
   OR sku_code = '1294814'
   OR sku_code = '1294814GTGT';

-- 1288548GT: CY | $575/yr | Avg 2.1/wk | CV=0.8000 | Cost $5.34 (XYZ estimated)
UPDATE skus SET
  unit_cost = 5.3390,
  unit_weight = 0.8598,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 575.27,
  avg_weekly_demand = 2.0721,
  cv_demand = 0.8000,
  dimensions_cbm = 0.001262,
  length_in = 7.25,
  width_in = 2.50,
  height_in = 4.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1288548GT'
   OR sku_code = '1288548'
   OR sku_code = '1288548GTGT';

-- 1294839GT: CY | $573/yr | Avg 2.0/wk | CV=0.8000 | Cost $5.54 (XYZ estimated)
UPDATE skus SET
  unit_cost = 5.5368,
  unit_weight = 2.0283,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 573.24,
  avg_weekly_demand = 1.9910,
  cv_demand = 0.8000,
  dimensions_cbm = 0.001184,
  length_in = 4.25,
  width_in = 4.25,
  height_in = 4.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1294839GT'
   OR sku_code = '1294839'
   OR sku_code = '1294839GTGT';

-- 214375GT: CY | $569/yr | Avg 2.1/wk | CV=0.8000 | Cost $5.26 (XYZ estimated)
UPDATE skus SET
  unit_cost = 5.2577,
  unit_weight = 3.2849,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 568.97,
  avg_weekly_demand = 2.0811,
  cv_demand = 0.8000,
  dimensions_cbm = 0.002704,
  length_in = 10.00,
  width_in = 3.00,
  height_in = 5.50,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '214375GT'
   OR sku_code = '214375'
   OR sku_code = '214375GTGT';

-- 1284781GT: CY | $533/yr | Avg 1.9/wk | CV=0.8000 | Cost $5.52 (XYZ estimated)
UPDATE skus SET
  unit_cost = 5.5209,
  unit_weight = 1.8034,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 532.80,
  avg_weekly_demand = 1.8559,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000784,
  length_in = 8.50,
  width_in = 1.50,
  height_in = 3.75,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1284781GT'
   OR sku_code = '1284781'
   OR sku_code = '1284781GTGT';

-- 1303372GT: CY | $488/yr | Avg 7.6/wk | CV=0.8000 | Cost $1.24 (XYZ estimated)
UPDATE skus SET
  unit_cost = 1.2378,
  unit_weight = 0.0661,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 488.25,
  avg_weekly_demand = 7.5856,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000007,
  length_in = 2.25,
  width_in = 0.75,
  height_in = 0.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1303372GT'
   OR sku_code = '1303372'
   OR sku_code = '1303372GTGT';

-- 1274333GT: CY | $431/yr | Avg 3.9/wk | CV=0.8000 | Cost $2.15 (XYZ estimated)
UPDATE skus SET
  unit_cost = 2.1480,
  unit_weight = 60.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 430.69,
  avg_weekly_demand = 3.8559,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000160,
  length_in = 3.25,
  width_in = 4.00,
  height_in = 0.75,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1274333GT'
   OR sku_code = '1274333'
   OR sku_code = '1274333GTGT';

-- 1288549GT: CY | $409/yr | Avg 1.8/wk | CV=0.8000 | Cost $4.35 (XYZ estimated)
UPDATE skus SET
  unit_cost = 4.3470,
  unit_weight = 1.6116,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 409.32,
  avg_weekly_demand = 1.8108,
  cv_demand = 0.8000,
  dimensions_cbm = 0.001323,
  length_in = 9.50,
  width_in = 2.00,
  height_in = 4.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1288549GT'
   OR sku_code = '1288549'
   OR sku_code = '1288549GTGT';

-- 1291069GT: CY | $358/yr | Avg 1.8/wk | CV=0.8000 | Cost $3.75 (XYZ estimated)
UPDATE skus SET
  unit_cost = 3.7451,
  unit_weight = 0.6526,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 357.90,
  avg_weekly_demand = 1.8378,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000999,
  length_in = 6.25,
  width_in = 3.00,
  height_in = 3.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1291069GT'
   OR sku_code = '1291069'
   OR sku_code = '1291069GTGT';

-- 1294232GT: CY | $337/yr | Avg 1.7/wk | CV=0.8000 | Cost $3.89 (XYZ estimated)
UPDATE skus SET
  unit_cost = 3.8908,
  unit_weight = 0.9259,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 337.21,
  avg_weekly_demand = 1.6667,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000512,
  length_in = 6.25,
  width_in = 2.00,
  height_in = 2.50,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1294232GT'
   OR sku_code = '1294232'
   OR sku_code = '1294232GTGT';

-- 1296915GT: CY | $331/yr | Avg 5.8/wk | CV=0.8000 | Cost $1.10 (XYZ estimated)
UPDATE skus SET
  unit_cost = 1.1043,
  unit_weight = 0.1433,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 331.09,
  avg_weekly_demand = 5.7658,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000054,
  length_in = 5.25,
  width_in = 2.50,
  height_in = 0.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1296915GT'
   OR sku_code = '1296915'
   OR sku_code = '1296915GTGT';

-- 1288944GT: CY | $298/yr | Avg 1.8/wk | CV=0.8000 | Cost $3.11 (XYZ estimated)
UPDATE skus SET
  unit_cost = 3.1079,
  unit_weight = 0.7249,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 298.46,
  avg_weekly_demand = 1.8468,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000516,
  length_in = 7.00,
  width_in = 3.00,
  height_in = 1.50,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1288944GT'
   OR sku_code = '1288944'
   OR sku_code = '1288944GTGT';

-- 1321409GT: CZ | $184/yr | Avg 0.1/wk | CV=1.2000 | Cost $26.25 (XYZ estimated)
UPDATE skus SET
  unit_cost = 26.2500,
  unit_weight = 0.6448,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 184.41,
  avg_weekly_demand = 0.1351,
  cv_demand = 1.2000,
  dimensions_cbm = 0.020625,
  length_in = 21.65,
  width_in = 9.84,
  height_in = 5.91,
  supplier_code = 'Nuode',
  updated_at = NOW()
WHERE sku_code = '1321409GT'
   OR sku_code = '1321409'
   OR sku_code = '1321409GTGT';

-- 1288550GT: CY | $156/yr | Avg 1.9/wk | CV=0.8000 | Cost $1.55 (XYZ estimated)
UPDATE skus SET
  unit_cost = 1.5455,
  unit_weight = 0.2998,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 155.66,
  avg_weekly_demand = 1.9369,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000300,
  length_in = 3.25,
  width_in = 2.50,
  height_in = 2.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1288550GT'
   OR sku_code = '1288550'
   OR sku_code = '1288550GTGT';

-- 1326749GT: CZ | $121/yr | Avg 0.2/wk | CV=1.2000 | Cost $13.56 (XYZ estimated)
UPDATE skus SET
  unit_cost = 13.5600,
  unit_weight = 0.1432,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 120.72,
  avg_weekly_demand = 0.1712,
  cv_demand = 1.2000,
  dimensions_cbm = 0.006786,
  length_in = 11.42,
  width_in = 10.24,
  height_in = 3.54,
  supplier_code = 'Nuode',
  updated_at = NOW()
WHERE sku_code = '1326749GT'
   OR sku_code = '1326749'
   OR sku_code = '1326749GTGT';

-- 1326751GT: CZ | $113/yr | Avg 0.3/wk | CV=1.2000 | Cost $8.07 (XYZ estimated)
UPDATE skus SET
  unit_cost = 8.0700,
  unit_weight = 0.1488,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 113.43,
  avg_weekly_demand = 0.2703,
  cv_demand = 1.2000,
  dimensions_cbm = 0.020625,
  length_in = 21.65,
  width_in = 9.84,
  height_in = 5.91,
  supplier_code = 'Nuode',
  updated_at = NOW()
WHERE sku_code = '1326751GT'
   OR sku_code = '1326751'
   OR sku_code = '1326751GTGT';

-- 227164GT: CY | $95/yr | Avg 2.0/wk | CV=0.8000 | Cost $0.93 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.9331,
  unit_weight = 0.2646,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 95.30,
  avg_weekly_demand = 1.9640,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000040,
  length_in = 3.25,
  width_in = 3.00,
  height_in = 0.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '227164GT'
   OR sku_code = '227164'
   OR sku_code = '227164GTGT';

-- 1326750GT: CZ | $86/yr | Avg 0.2/wk | CV=1.2000 | Cost $9.68 (XYZ estimated)
UPDATE skus SET
  unit_cost = 9.6800,
  unit_weight = 0.0661,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 86.18,
  avg_weekly_demand = 0.1712,
  cv_demand = 1.2000,
  dimensions_cbm = 0.006786,
  length_in = 11.42,
  width_in = 10.24,
  height_in = 3.54,
  supplier_code = 'Nuode',
  updated_at = NOW()
WHERE sku_code = '1326750GT'
   OR sku_code = '1326750'
   OR sku_code = '1326750GTGT';

-- 1288777GT: CZ | $65/yr | Avg 0.1/wk | CV=1.2000 | Cost $15.45 (XYZ estimated)
UPDATE skus SET
  unit_cost = 15.4450,
  unit_weight = 3.6800,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 65.13,
  avg_weekly_demand = 0.0811,
  cv_demand = 1.2000,
  dimensions_cbm = 0.005945,
  length_in = 10.75,
  width_in = 9.00,
  height_in = 3.75,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1288777GT'
   OR sku_code = '1288777'
   OR sku_code = '1288777GTGT';

-- 1294711GT: CZ | $62/yr | Avg 0.5/wk | CV=1.2000 | Cost $2.42 (XYZ estimated)
UPDATE skus SET
  unit_cost = 2.4236,
  unit_weight = 0.3800,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 62.45,
  avg_weekly_demand = 0.4955,
  cv_demand = 1.2000,
  dimensions_cbm = 0.000320,
  length_in = 3.00,
  width_in = 3.25,
  height_in = 2.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1294711GT'
   OR sku_code = '1294711'
   OR sku_code = '1294711GTGT';

-- 228362GT: CY | $60/yr | Avg 2.1/wk | CV=0.8000 | Cost $0.56 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.5647,
  unit_weight = 0.1323,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 60.32,
  avg_weekly_demand = 2.0541,
  cv_demand = 0.8000,
  dimensions_cbm = 0.000010,
  length_in = 2.50,
  width_in = 1.00,
  height_in = 0.25,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '228362GT'
   OR sku_code = '228362'
   OR sku_code = '228362GTGT';

-- 1260198GT: CZ | $0/yr | Avg 0.0/wk | CV=NULL | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.0000,
  cv_demand = NULL,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '1260198GT'
   OR sku_code = '1260198'
   OR sku_code = '1260198GTGT';

-- 1260200GT: CY | $0/yr | Avg 1.1/wk | CV=0.8000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 1.0811,
  cv_demand = 0.8000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '1260200GT'
   OR sku_code = '1260200'
   OR sku_code = '1260200GTGT';

-- 1260307GT: CZ | $0/yr | Avg 0.3/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.2883,
  cv_demand = 1.2000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '1260307GT'
   OR sku_code = '1260307'
   OR sku_code = '1260307GTGT';

-- 1264224GT: CZ | $0/yr | Avg 0.5/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.5405,
  cv_demand = 1.2000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '1264224GT'
   OR sku_code = '1264224'
   OR sku_code = '1264224GTGT';

-- 1299483GT: CZ | $0/yr | Avg 0.3/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.2703,
  cv_demand = 1.2000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '1299483GT'
   OR sku_code = '1299483'
   OR sku_code = '1299483GTGT';

-- 132383GT: CY | $0/yr | Avg 1.1/wk | CV=0.8000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 1.0811,
  cv_demand = 0.8000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '132383GT'
   OR sku_code = '132383'
   OR sku_code = '132383GTGT';

-- 132385GT: CY | $0/yr | Avg 1.1/wk | CV=0.8000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 1.0811,
  cv_demand = 0.8000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '132385GT'
   OR sku_code = '132385'
   OR sku_code = '132385GTGT';

-- 132517GT: CZ | $0/yr | Avg 0.7/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.7207,
  cv_demand = 1.2000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '132517GT'
   OR sku_code = '132517'
   OR sku_code = '132517GTGT';

-- 132525GT: CZ | $0/yr | Avg 0.5/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.5045,
  cv_demand = 1.2000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '132525GT'
   OR sku_code = '132525'
   OR sku_code = '132525GTGT';

-- 229579GT: CY | $0/yr | Avg 7.7/wk | CV=0.8000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Y',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 7.6577,
  cv_demand = 0.8000,
  supplier_code = 'AMC',
  updated_at = NOW()
WHERE sku_code = '229579GT'
   OR sku_code = '229579'
   OR sku_code = '229579GTGT';

-- 1290292GT: CZ | $0/yr | Avg 0.0/wk | CV=NULL | Cost $7.14 (XYZ estimated)
UPDATE skus SET
  unit_cost = 7.1385,
  unit_weight = 1.4153,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.0000,
  cv_demand = NULL,
  dimensions_cbm = 0.004719,
  length_in = 12.00,
  width_in = 6.00,
  height_in = 4.00,
  supplier_code = 'TianJin',
  updated_at = NOW()
WHERE sku_code = '1290292GT'
   OR sku_code = '1290292'
   OR sku_code = '1290292GTGT';

-- 1323355GT: CZ | $0/yr | Avg 0.0/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.0450,
  cv_demand = 1.2000,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1323355GT'
   OR sku_code = '1323355'
   OR sku_code = '1323355GTGT';

-- 1327545GT: CZ | $0/yr | Avg 0.0/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.0090,
  cv_demand = 1.2000,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1327545GT'
   OR sku_code = '1327545'
   OR sku_code = '1327545GTGT';

-- 1327546GT: CZ | $0/yr | Avg 0.0/wk | CV=1.2000 | Cost $0.00 (XYZ estimated)
UPDATE skus SET
  unit_cost = 0.0000,
  unit_weight = 0.0000,
  abc_class = 'C',
  xyz_class = 'Z',
  annual_consumption_value = 0.00,
  avg_weekly_demand = 0.0090,
  cv_demand = 1.2000,
  supplier_code = 'ZhongXing',
  updated_at = NOW()
WHERE sku_code = '1327546GT'
   OR sku_code = '1327546'
   OR sku_code = '1327546GTGT';


-- =============================================
-- PART 3: SKU Classification View
-- =============================================

CREATE OR REPLACE VIEW v_sku_classification AS
SELECT
  s.id,
  s.sku_code,
  s.part_model,
  s.description,
  s.supplier_code,
  s.abc_class,
  s.xyz_class,
  COALESCE(s.abc_class, '') || COALESCE(s.xyz_class, '') as matrix_cell,
  s.unit_cost,
  s.annual_consumption_value,
  s.avg_weekly_demand,
  s.cv_demand,
  s.safety_stock_weeks,
  s.reorder_point,
  s.moq,
  s.lead_time_weeks,
  s.unit_weight,
  s.qty_per_container,
  s.dimensions_cbm,
  s.length_in,
  s.width_in,
  s.height_in
FROM skus s
WHERE s.abc_class IS NOT NULL
ORDER BY
  CASE s.abc_class WHEN 'A' THEN 1 WHEN 'B' THEN 2 ELSE 3 END,
  CASE s.xyz_class WHEN 'X' THEN 1 WHEN 'Y' THEN 2 ELSE 3 END,
  s.annual_consumption_value DESC NULLS LAST;


-- =============================================
-- PART 4: Classification Policies Table (9-Grid)
-- =============================================

CREATE TABLE IF NOT EXISTS classification_policies (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  matrix_cell TEXT NOT NULL UNIQUE,
  service_level NUMERIC NOT NULL,
  target_woh NUMERIC NOT NULL,
  review_frequency TEXT NOT NULL,
  replenishment_method TEXT NOT NULL,
  safety_stock_multiplier NUMERIC DEFAULT 1.0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Netstock-recommended default policies
INSERT INTO classification_policies (matrix_cell, service_level, target_woh, review_frequency, replenishment_method, notes) VALUES
  ('AX', 0.97, 4,  'weekly',    'auto',          'High value + stable: tight control, auto replenish'),
  ('AY', 0.95, 5,  'weekly',    'auto',          'High value + moderate: buffer slightly more'),
  ('AZ', 0.93, 6,  'weekly',    'manual_review', 'High value + erratic: human review before ordering'),
  ('BX', 0.95, 5,  'biweekly',  'auto',          'Medium value + stable: standard auto'),
  ('BY', 0.93, 6,  'biweekly',  'auto',          'Medium value + moderate: moderate buffer'),
  ('BZ', 0.90, 8,  'biweekly',  'manual_review', 'Medium value + erratic: review before ordering'),
  ('CX', 0.92, 6,  'monthly',   'auto',          'Low value + stable: less frequent review'),
  ('CY', 0.90, 8,  'monthly',   'auto',          'Low value + moderate: bulk order'),
  ('CZ', 0.85, 10, 'monthly',   'on_demand',     'Low value + erratic: order only when needed')
ON CONFLICT (matrix_cell) DO UPDATE SET
  service_level = EXCLUDED.service_level,
  target_woh = EXCLUDED.target_woh,
  review_frequency = EXCLUDED.review_frequency,
  replenishment_method = EXCLUDED.replenishment_method,
  notes = EXCLUDED.notes,
  updated_at = NOW();


-- =============================================
-- PART 5: Permissions
-- =============================================

GRANT ALL ON classification_policies TO authenticated;
GRANT SELECT ON v_sku_classification TO authenticated;
